include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, third_party/**]
  language:
    strict-raw-types: true

linter:
  rules:
    - prefer_final_locals
    - prefer_const_declarations
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
