// Copyright (c) 2022, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.


// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "jni.h"
#include "dartjni.h"

thread_local JNIEnv *jniEnv;
JniContext jni;

JniContext (*context_getter)(void);
JNIEnv *(*env_getter)(void);

void setJniGetters(JniContext (*cg)(void),
        JNIEnv *(*eg)(void)) {
    context_getter = cg;
    env_getter = eg;
}

// com.github.dart_lang.jnigen.simple_package.Example
jclass _c_com_github_dart_lang_jnigen_simple_package_Example = NULL;

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_ctor = NULL;
FFI_PLUGIN_EXPORT
jobject com_github_dart_lang_jnigen_simple_package_Example_ctor() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (jobject)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_ctor, "<init>", "()V");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_ctor == NULL) return (jobject)0;
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _m_com_github_dart_lang_jnigen_simple_package_Example_ctor);
    return to_global_ref(_result);
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_getAux = NULL;
FFI_PLUGIN_EXPORT
jobject com_github_dart_lang_jnigen_simple_package_Example_getAux() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (jobject)0;
    load_static_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_getAux, "getAux", "()Lcom/github/dart_lang/jnigen/simple_package/Example$Aux;");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_getAux == NULL) return (jobject)0;
    jobject _result = (*jniEnv)->CallStaticObjectMethod(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _m_com_github_dart_lang_jnigen_simple_package_Example_getAux);
    return to_global_ref(_result);
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_addInts = NULL;
FFI_PLUGIN_EXPORT
int32_t com_github_dart_lang_jnigen_simple_package_Example_addInts(int32_t a, int32_t b) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (int32_t)0;
    load_static_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_addInts, "addInts", "(II)I");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_addInts == NULL) return (int32_t)0;
    int32_t _result = (*jniEnv)->CallStaticIntMethod(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _m_com_github_dart_lang_jnigen_simple_package_Example_addInts, a, b);
    return _result;
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_getSelf = NULL;
FFI_PLUGIN_EXPORT
jobject com_github_dart_lang_jnigen_simple_package_Example_getSelf(jobject self_) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (jobject)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_getSelf, "getSelf", "()Lcom/github/dart_lang/jnigen/simple_package/Example;");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_getSelf == NULL) return (jobject)0;
    jobject _result = (*jniEnv)->CallObjectMethod(jniEnv, self_, _m_com_github_dart_lang_jnigen_simple_package_Example_getSelf);
    return to_global_ref(_result);
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_getNum = NULL;
FFI_PLUGIN_EXPORT
int32_t com_github_dart_lang_jnigen_simple_package_Example_getNum(jobject self_) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (int32_t)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_getNum, "getNum", "()I");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_getNum == NULL) return (int32_t)0;
    int32_t _result = (*jniEnv)->CallIntMethod(jniEnv, self_, _m_com_github_dart_lang_jnigen_simple_package_Example_getNum);
    return _result;
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_setNum = NULL;
FFI_PLUGIN_EXPORT
void com_github_dart_lang_jnigen_simple_package_Example_setNum(jobject self_, int32_t num) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (void)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_setNum, "setNum", "(I)V");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_setNum == NULL) return (void)0;
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_com_github_dart_lang_jnigen_simple_package_Example_setNum, num);
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example_throwException = NULL;
FFI_PLUGIN_EXPORT
void com_github_dart_lang_jnigen_simple_package_Example_throwException() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (void)0;
    load_static_method(_c_com_github_dart_lang_jnigen_simple_package_Example, &_m_com_github_dart_lang_jnigen_simple_package_Example_throwException, "throwException", "()V");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example_throwException == NULL) return (void)0;
    (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _m_com_github_dart_lang_jnigen_simple_package_Example_throwException);
}

jfieldID _f_com_github_dart_lang_jnigen_simple_package_Example_aux = NULL;
FFI_PLUGIN_EXPORT
jobject get_com_github_dart_lang_jnigen_simple_package_Example_aux() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (jobject)0;
    load_static_field(_c_com_github_dart_lang_jnigen_simple_package_Example, &_f_com_github_dart_lang_jnigen_simple_package_Example_aux, "aux","Lcom/github/dart_lang/jnigen/simple_package/Example$Aux;");
    return to_global_ref((*jniEnv)->GetStaticObjectField(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _f_com_github_dart_lang_jnigen_simple_package_Example_aux));
}

FFI_PLUGIN_EXPORT
void set_com_github_dart_lang_jnigen_simple_package_Example_aux(jobject value) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (void)0;
    load_static_field(_c_com_github_dart_lang_jnigen_simple_package_Example, &_f_com_github_dart_lang_jnigen_simple_package_Example_aux, "aux","Lcom/github/dart_lang/jnigen/simple_package/Example$Aux;");
    ((*jniEnv)->SetStaticObjectField(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _f_com_github_dart_lang_jnigen_simple_package_Example_aux, value));
}


jfieldID _f_com_github_dart_lang_jnigen_simple_package_Example_num = NULL;
FFI_PLUGIN_EXPORT
int32_t get_com_github_dart_lang_jnigen_simple_package_Example_num() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (int32_t)0;
    load_static_field(_c_com_github_dart_lang_jnigen_simple_package_Example, &_f_com_github_dart_lang_jnigen_simple_package_Example_num, "num","I");
    return ((*jniEnv)->GetStaticIntField(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _f_com_github_dart_lang_jnigen_simple_package_Example_num));
}

FFI_PLUGIN_EXPORT
void set_com_github_dart_lang_jnigen_simple_package_Example_num(int32_t value) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example, "com/github/dart_lang/jnigen/simple_package/Example");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example == NULL) return (void)0;
    load_static_field(_c_com_github_dart_lang_jnigen_simple_package_Example, &_f_com_github_dart_lang_jnigen_simple_package_Example_num, "num","I");
    ((*jniEnv)->SetStaticIntField(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example, _f_com_github_dart_lang_jnigen_simple_package_Example_num, value));
}


// com.github.dart_lang.jnigen.simple_package.Example$Aux
jclass _c_com_github_dart_lang_jnigen_simple_package_Example__Aux = NULL;

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example__Aux_ctor = NULL;
FFI_PLUGIN_EXPORT
jobject com_github_dart_lang_jnigen_simple_package_Example__Aux_ctor(uint8_t value) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, "com/github/dart_lang/jnigen/simple_package/Example$Aux");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example__Aux == NULL) return (jobject)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, &_m_com_github_dart_lang_jnigen_simple_package_Example__Aux_ctor, "<init>", "(Z)V");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example__Aux_ctor == NULL) return (jobject)0;
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_com_github_dart_lang_jnigen_simple_package_Example__Aux, _m_com_github_dart_lang_jnigen_simple_package_Example__Aux_ctor, value);
    return to_global_ref(_result);
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example__Aux_getValue = NULL;
FFI_PLUGIN_EXPORT
uint8_t com_github_dart_lang_jnigen_simple_package_Example__Aux_getValue(jobject self_) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, "com/github/dart_lang/jnigen/simple_package/Example$Aux");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example__Aux == NULL) return (uint8_t)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, &_m_com_github_dart_lang_jnigen_simple_package_Example__Aux_getValue, "getValue", "()Z");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example__Aux_getValue == NULL) return (uint8_t)0;
    uint8_t _result = (*jniEnv)->CallBooleanMethod(jniEnv, self_, _m_com_github_dart_lang_jnigen_simple_package_Example__Aux_getValue);
    return _result;
}

jmethodID _m_com_github_dart_lang_jnigen_simple_package_Example__Aux_setValue = NULL;
FFI_PLUGIN_EXPORT
void com_github_dart_lang_jnigen_simple_package_Example__Aux_setValue(jobject self_, uint8_t value) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, "com/github/dart_lang/jnigen/simple_package/Example$Aux");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example__Aux == NULL) return (void)0;
    load_method(_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, &_m_com_github_dart_lang_jnigen_simple_package_Example__Aux_setValue, "setValue", "(Z)V");
    if (_m_com_github_dart_lang_jnigen_simple_package_Example__Aux_setValue == NULL) return (void)0;
    (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_com_github_dart_lang_jnigen_simple_package_Example__Aux_setValue, value);
}

jfieldID _f_com_github_dart_lang_jnigen_simple_package_Example__Aux_value = NULL;
FFI_PLUGIN_EXPORT
uint8_t get_com_github_dart_lang_jnigen_simple_package_Example__Aux_value(jobject self_) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, "com/github/dart_lang/jnigen/simple_package/Example$Aux");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example__Aux == NULL) return (uint8_t)0;
    load_field(_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, &_f_com_github_dart_lang_jnigen_simple_package_Example__Aux_value, "value","Z");
    return ((*jniEnv)->GetBooleanField(jniEnv, self_, _f_com_github_dart_lang_jnigen_simple_package_Example__Aux_value));
}

FFI_PLUGIN_EXPORT
void set_com_github_dart_lang_jnigen_simple_package_Example__Aux_value(jobject self_, uint8_t value) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, "com/github/dart_lang/jnigen/simple_package/Example$Aux");
    if (_c_com_github_dart_lang_jnigen_simple_package_Example__Aux == NULL) return (void)0;
    load_field(_c_com_github_dart_lang_jnigen_simple_package_Example__Aux, &_f_com_github_dart_lang_jnigen_simple_package_Example__Aux_value, "value","Z");
    ((*jniEnv)->SetBooleanField(jniEnv, self_, _f_com_github_dart_lang_jnigen_simple_package_Example__Aux_value, value));
}


// com.github.dart_lang.jnigen.pkg2.C2
jclass _c_com_github_dart_lang_jnigen_pkg2_C2 = NULL;

jmethodID _m_com_github_dart_lang_jnigen_pkg2_C2_ctor = NULL;
FFI_PLUGIN_EXPORT
jobject com_github_dart_lang_jnigen_pkg2_C2_ctor() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_pkg2_C2, "com/github/dart_lang/jnigen/pkg2/C2");
    if (_c_com_github_dart_lang_jnigen_pkg2_C2 == NULL) return (jobject)0;
    load_method(_c_com_github_dart_lang_jnigen_pkg2_C2, &_m_com_github_dart_lang_jnigen_pkg2_C2_ctor, "<init>", "()V");
    if (_m_com_github_dart_lang_jnigen_pkg2_C2_ctor == NULL) return (jobject)0;
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_com_github_dart_lang_jnigen_pkg2_C2, _m_com_github_dart_lang_jnigen_pkg2_C2_ctor);
    return to_global_ref(_result);
}

jfieldID _f_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT = NULL;
FFI_PLUGIN_EXPORT
int32_t get_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT() {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_pkg2_C2, "com/github/dart_lang/jnigen/pkg2/C2");
    if (_c_com_github_dart_lang_jnigen_pkg2_C2 == NULL) return (int32_t)0;
    load_static_field(_c_com_github_dart_lang_jnigen_pkg2_C2, &_f_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT, "CONSTANT","I");
    return ((*jniEnv)->GetStaticIntField(jniEnv, _c_com_github_dart_lang_jnigen_pkg2_C2, _f_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT));
}

FFI_PLUGIN_EXPORT
void set_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT(int32_t value) {
    load_env();
    load_class_gr(&_c_com_github_dart_lang_jnigen_pkg2_C2, "com/github/dart_lang/jnigen/pkg2/C2");
    if (_c_com_github_dart_lang_jnigen_pkg2_C2 == NULL) return (void)0;
    load_static_field(_c_com_github_dart_lang_jnigen_pkg2_C2, &_f_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT, "CONSTANT","I");
    ((*jniEnv)->SetStaticIntField(jniEnv, _c_com_github_dart_lang_jnigen_pkg2_C2, _f_com_github_dart_lang_jnigen_pkg2_C2_CONSTANT, value));
}


