name: jni_gen_test
description: Simple test for jni_gen
version: 0.0.1
homepage: https://github.com/dart-lang/jni_gen
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  jni:
    path: ../jni/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  jni_gen:
    path: ../jni_gen/
