name: pdf_info
description: Dart standalone example using jnigen PDFBox bindings.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  path: ^1.8.0
  jni:
    path: ../../../../jni/
  pdfbox_plugin:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
