# Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: kotlin_plugin
description: Example of using jnigen to generate bindings for Kotlin.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0-444.3.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  jni:
    path: ../../../jni

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  jnigen:
    path: ../../

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
