/// Run from templates directory

import 'dart:io' as io;
import 'package:path/path.dart';

var targetTypes = {
  "String": "String",
  "Object": "JniObject",
  "Boolean": "bool",
  "Byte": "int",
  "Char": "int",
  "Short": "int",
  "Int": "int",
  "Long": "int",
  "Float": "double",
  "Double": "double",
  "Void": "void"
};

var resultConverters = {
  "String": (String resultVar) => "final str = _env.asDartString($resultVar);"
      "_env.DeleteLocalRef($resultVar);"
      "return str",
  "Object": (String resultVar) =>
      "return JniObject.of(_env, $resultVar, nullptr)",
  "Boolean": (String resultVar) => "return $resultVar != 0",
};

var invokeResultConverters = {
  "String": (String resultVar) => "final str = env.asDartString($resultVar);"
      "env.DeleteLocalRef($resultVar);"
      "env.DeleteLocalRef(cls);"
      "return str",
  "Object": (String resultVar) =>
      "return JniObject.of(env, $resultVar, nullptr)",
  "Boolean": (String resultVar) => "return $resultVar != 0",
};

void main(List<String> args) {
  final script = io.Platform.script;
  final scriptDir = dirname(script.toFilePath(windows: io.Platform.isWindows));
  String getTemplate(String name) {
    return io.File(join(scriptDir, 'templates', name)).readAsStringSync();
  }

  final methodTemplates = getTemplate('JniObject_MethodCalls');
  final fieldTemplates = getTemplate('JniObject_Fields');
  final invokeTemplates = getTemplate('Invoke_Static_Methods');
  final retrieveTemplates = getTemplate('Retrieve_Static_Fields');

  var outputDir = join("lib", "src");
  var sInst = StringBuffer();
  var sStatic = StringBuffer();
  var sInvoke = StringBuffer();
  var outPutPaths = {
    sInst: join(outputDir, "jni_object_methods_generated.dart"),
    sStatic: join(outputDir, "jni_class_methods_generated.dart"),
    sInvoke: join(outputDir, "direct_methods_generated.dart")
  };
  for (var s in [sInst, sStatic, sInvoke]) {
    s.write("// Autogenerated; DO NOT EDIT\n"
        "// Generated by running the script in tool/gen_aux_methods.dart\n");
  }

  sInst.write("part of 'jni_object.dart';\n\n");
  sStatic.write("part of 'jni_class.dart';\n\n");
  sInvoke.write("part of 'jni.dart';\n\n");

  sInst.write("extension JniObjectCallMethods on JniObject {");
  sStatic.write("extension JniClassCallMethods on JniClass {");
  sInvoke.write("extension JniInvokeMethods on Jni {");

  for (var t in targetTypes.keys) {
    void write(String template) {
      final resultConverter =
          resultConverters[t] ?? (resultVar) => "return $resultVar";
      final skel = template
          .replaceAll("{TYPE}", t == "String" ? "Object" : t)
          .replaceAll("{PTYPE}", t)
          .replaceAll("{TARGET_TYPE}", targetTypes[t]!)
          .replaceAll("{RESULT}", resultConverter("result"));
      final inst_ =
          skel.replaceAll("{STATIC}", "").replaceAll("{THIS}", "_obj");
      final static_ =
          skel.replaceAll("{STATIC}", "Static").replaceAll("{THIS}", "_cls");
      sInst.write(inst_);
      sStatic.write(static_);
    }

    write(methodTemplates);
    if (t != "Void") {
      write(fieldTemplates);
    }
    var invokeResultConverter =
        (invokeResultConverters[t] ?? (String r) => "return $r");
    void writeI(String template) {
      final replaced = template
          .replaceAll("{TYPE}", t == "String" ? "Object" : t)
          .replaceAll("{PTYPE}", t)
          .replaceAll("{TARGET_TYPE}", targetTypes[t]!)
          .replaceAll(
              "{CLS_REF_DEL}",
              t == "Object" || t == "String"
                  ? ""
                  : "env.DeleteLocalRef(cls);\n")
          .replaceAll("{INVOKE_RESULT}", invokeResultConverter("result"));
      sInvoke.write(replaced);
    }

    writeI(invokeTemplates);
    if (t != "Void") {
      writeI(retrieveTemplates);
    }
  }
  sInst.write("}");
  sStatic.write("}");
  sInvoke.write("}");
  for (var s in [sInst, sStatic, sInvoke]) {
    var outputFile = io.File(outPutPaths[s]!);
    outputFile.writeAsStringSync(s.toString(), flush: true);
  }
  io.stderr.write("Running dart format..\n");
  io.Process.run("dart", ["format", ...outPutPaths.values]);
}
